### ISSUE TITLE
bpm of floor grid changes after reloading file

### ISSUE THREAD

**Issue by ashauryn** [squeaksies/MediocreMapper#17]
After placing all my notes on a 127 bpm song with 1/8 cursor precision, when the song was reloaded after closing the program, the floor grid no longer matched up with the notes as before. Now I can't do the lighting because I can't place blocks that match with my note placements.  This has happened twice.

**Comment by Thynix** [comment]
Are you saying it doesn't happen every time? How are you setting the BPM? Have you ever changed the BPM?

**Comment by ashauryn** [comment]
Oh, to answer your question I am setting the BPM in song-info and hitting "save song info", then after I am editing the level, I go to the options screen and set the bpm again there.

**Comment by Thynix** [comment]
Did the BPM listed in the song info also change when this happened, or is this a spookier problem?

**Comment by Thynix** [comment]
My understanding is the BPM is primarily used (within the editor anyway) to align the grid, so that notes you timed previously stayed timed makes sense. What's not making sense to me is how someone else might reproduce the problem you're having with it changing in order to debug it. Can you post `info.json` before and after the change? (Or I suppose you may only have after currently, unless your machine managed to save earlier revisions with file history or something.)

**Comment by ashauryn** [comment]
I see. Unfortunately I don't have the original. I'll make backups from now
on and update if it happens again. Thanks for the response!

**Comment by squeaksies** [comment]
this isn't a problem of mediocre, rather a feature it doesn't have. there are a few python scripts floating about that will fix your issue, but do not change the BPM after placing notes if you want everything to stay in line, it's just a limitation of the editor. 

The number of people who map at an incorrect BPM and later change it is incredibly limited, and as such i have no plans to introduce a feature like that at this time.
